# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: misc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='misc.proto',
  package='jzs.msg.misc',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\nmisc.proto\x12\x0cjzs.msg.misc\"&\n\x04\x43ode\x12\x0e\n\x06jzcode\x18\x01 \x02(\r\x12\x0e\n\x06symbol\x18\x02 \x02(\t\"<\n\tCodeTable\x12\x0c\n\x04\x64\x61te\x18\x01 \x02(\r\x12!\n\x05\x63odes\x18\x02 \x03(\x0b\x32\x12.jzs.msg.misc.Code\"3\n\x0fLowHeartBeatReq\x12\x0e\n\x06req_id\x18\x01 \x02(\r\x12\x10\n\x08req_time\x18\x02 \x02(\x04\"E\n\x0fLowHeartBeatRsp\x12\x0e\n\x06req_id\x18\x01 \x02(\r\x12\x10\n\x08req_time\x18\x02 \x02(\x04\x12\x10\n\x08rsp_time\x18\x03 \x02(\x04')
)




_CODE = _descriptor.Descriptor(
  name='Code',
  full_name='jzs.msg.misc.Code',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='jzcode', full_name='jzs.msg.misc.Code.jzcode', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='symbol', full_name='jzs.msg.misc.Code.symbol', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=66,
)


_CODETABLE = _descriptor.Descriptor(
  name='CodeTable',
  full_name='jzs.msg.misc.CodeTable',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='date', full_name='jzs.msg.misc.CodeTable.date', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='codes', full_name='jzs.msg.misc.CodeTable.codes', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=128,
)


_LOWHEARTBEATREQ = _descriptor.Descriptor(
  name='LowHeartBeatReq',
  full_name='jzs.msg.misc.LowHeartBeatReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='req_id', full_name='jzs.msg.misc.LowHeartBeatReq.req_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='req_time', full_name='jzs.msg.misc.LowHeartBeatReq.req_time', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=181,
)


_LOWHEARTBEATRSP = _descriptor.Descriptor(
  name='LowHeartBeatRsp',
  full_name='jzs.msg.misc.LowHeartBeatRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='req_id', full_name='jzs.msg.misc.LowHeartBeatRsp.req_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='req_time', full_name='jzs.msg.misc.LowHeartBeatRsp.req_time', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rsp_time', full_name='jzs.msg.misc.LowHeartBeatRsp.rsp_time', index=2,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=252,
)

_CODETABLE.fields_by_name['codes'].message_type = _CODE
DESCRIPTOR.message_types_by_name['Code'] = _CODE
DESCRIPTOR.message_types_by_name['CodeTable'] = _CODETABLE
DESCRIPTOR.message_types_by_name['LowHeartBeatReq'] = _LOWHEARTBEATREQ
DESCRIPTOR.message_types_by_name['LowHeartBeatRsp'] = _LOWHEARTBEATRSP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Code = _reflection.GeneratedProtocolMessageType('Code', (_message.Message,), dict(
  DESCRIPTOR = _CODE,
  __module__ = 'misc_pb2'
  # @@protoc_insertion_point(class_scope:jzs.msg.misc.Code)
  ))
_sym_db.RegisterMessage(Code)

CodeTable = _reflection.GeneratedProtocolMessageType('CodeTable', (_message.Message,), dict(
  DESCRIPTOR = _CODETABLE,
  __module__ = 'misc_pb2'
  # @@protoc_insertion_point(class_scope:jzs.msg.misc.CodeTable)
  ))
_sym_db.RegisterMessage(CodeTable)

LowHeartBeatReq = _reflection.GeneratedProtocolMessageType('LowHeartBeatReq', (_message.Message,), dict(
  DESCRIPTOR = _LOWHEARTBEATREQ,
  __module__ = 'misc_pb2'
  # @@protoc_insertion_point(class_scope:jzs.msg.misc.LowHeartBeatReq)
  ))
_sym_db.RegisterMessage(LowHeartBeatReq)

LowHeartBeatRsp = _reflection.GeneratedProtocolMessageType('LowHeartBeatRsp', (_message.Message,), dict(
  DESCRIPTOR = _LOWHEARTBEATRSP,
  __module__ = 'misc_pb2'
  # @@protoc_insertion_point(class_scope:jzs.msg.misc.LowHeartBeatRsp)
  ))
_sym_db.RegisterMessage(LowHeartBeatRsp)


# @@protoc_insertion_point(module_scope)
