version: '3'
services:
  ctp: 
    container_name: ctp_tick
    image: "dcext"
    network_mode: "host"
    command: "bash run.sh"
    volumes: 
      - ./etc:/app/etc
      - ./run.sh:/app/run.sh
  jqbar:
    container_name: jqbar
    image: "dcext"
    network_mode: "host"
    command: "python dcext/mm/ctp/jqbar.py"
    volumes:
      - ./etc:/app/etc
  mdlink_ctp:
    container_name: mdlink_ctp
    image: "mdlink:test"
    network_mode: "host"
    command: /mdlink-1.2-linux/bin/mdlink_ctp future1
    volumes:
    - ./log:/mdlink-1.2-linux/data/log
    - ./etc:/mdlink-1.2-linux/etc
  hist:
    container_name: hist
    image: "dcext"
    network_mode: "host"
    command: "bash hist.sh"
    volumes:
       - ./etc:/app/etc
       - ./hist.sh:/app/hist.sh